<a href="https://colab.research.google.com/github/shrey-shetty/v/blob/main/1_Join_CSV_Files.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
@author: Ashish Chouhan
ETL with Pandas
"""

# Import Libraries required for Processing
import pandas as pd

# Setting file names used during execution process
# Input File :  Master file consists of Basic Information of Person and ID associated with it
#               Country_Code file consist of Country information associated with the ID
file_masters = 'masters.csv'
file_incoming = 'country_code.csv'

# Output File : Mastes_Dups file will hold the duplicate record present in the Master File if any
#               Output file will hold the complete informaiton of Person and Country for that ID.
file_masters_dups = 'masters_dups.csv'
file_out = 'output.csv'

# Read Master File to fetch Person Information

In [ ]:
# Read the Masters.csv file using pandas.read_csv function and populate the records into a Master Dataframe
df_masters = pd.read_csv('masters.csv')
df_masters

        ID      Lname      Fname                 Name
0   100001      Bogey    Hyberts       Bogey, Hyberts
1   100002  Mireielle   Lindauer  Mireielle, Lindauer
2   100003   Claiborn   Schacter   Claiborn, Schacter
3   100004  Hildagard   Eberhart  Hildagard, Eberhart
4   100005      Welsh  Westerman     Welsh, Westerman
5   100006    Wrennie      Platt       Wrennie, Platt
6   100007     Barris   Reynales     Barris, Reynales
7   100008     Wendye  Cicinelli    Wendye, Cicinelli
8   100009       Ethe     Slasor         Ethe, Slasor
9   100010  Valentine    Horsley   Valentine, Horsley
10  100002  Mireielle   Lindauer  Mireielle, Lindauer
11  100006    Wrennie      Platt       Wrennie, Platt

In [ ]:
# Sort records by IDs which are present in the Dataframe in Ascending Order
# TODO: Add your code here
df_masters=df_masters.sort_values(by='ID', ascending=True)

# Master Dataframe is having records which are arranged in the ascending order of ID
df_masters

        ID      Lname      Fname                 Name
0   100001      Bogey    Hyberts       Bogey, Hyberts
1   100002  Mireielle   Lindauer  Mireielle, Lindauer
10  100002  Mireielle   Lindauer  Mireielle, Lindauer
2   100003   Claiborn   Schacter   Claiborn, Schacter
3   100004  Hildagard   Eberhart  Hildagard, Eberhart
4   100005      Welsh  Westerman     Welsh, Westerman
11  100006    Wrennie      Platt       Wrennie, Platt
5   100006    Wrennie      Platt       Wrennie, Platt
6   100007     Barris   Reynales     Barris, Reynales
7   100008     Wendye  Cicinelli    Wendye, Cicinelli
8   100009       Ethe     Slasor         Ethe, Slasor
9   100010  Valentine    Horsley   Valentine, Horsley

In [ ]:
# Extract Duplicate record from Master Dataframe into a new dataframe
df_dups = df_masters[df_masters.duplicated(keep = 'first')]

df_dups

        ID      Lname     Fname                 Name
10  100002  Mireielle  Lindauer  Mireielle, Lindauer
5   100006    Wrennie     Platt       Wrennie, Platt

In [ ]:
# Export the output of duplicates to spreadsheet before deleting the duplicate record
df_dups.to_csv(file_masters_dups)

In [ ]:
# Remove Duplicate record based on ID from the Master Data Frame keeping only the first Record
# TODO: Add your code here
df_masters=df_masters.drop_duplicates(subset='ID', keep='first')
# Master Dataframe is having only Unique records and also is arranged in Ascending Order of ID
df_masters

        ID      Lname      Fname                 Name
0   100001      Bogey    Hyberts       Bogey, Hyberts
1   100002  Mireielle   Lindauer  Mireielle, Lindauer
2   100003   Claiborn   Schacter   Claiborn, Schacter
3   100004  Hildagard   Eberhart  Hildagard, Eberhart
4   100005      Welsh  Westerman     Welsh, Westerman
11  100006    Wrennie      Platt       Wrennie, Platt
6   100007     Barris   Reynales     Barris, Reynales
7   100008     Wendye  Cicinelli    Wendye, Cicinelli
8   100009       Ethe     Slasor         Ethe, Slasor
9   100010  Valentine    Horsley   Valentine, Horsley

In [ ]:
# Read Country_Code File to fetch Country Information

# Read the Country_Code.csv file using pandas.read_csv function and populate the records into a secondary Dataframe
# TODO: Add your code here
df_incoming=pd.read_csv('country_code.csv')
df_incoming

       ID Country
0  100001     USA
1  100002     USA
2  100003      UK
3  100008      UK
4  100009   China
5  100010     USA

# Process to Merge(Join) Two Tables present in two different dataframe

In [ ]:
# Join dataframe and populate into a new dataframe with Right Outer Join such that Master Dataframe (df_masters) is on left, Secondary Dataframe (df_incoming) is on right
df_join_right = pd.merge(df_masters, df_incoming, how='right', on=['ID'])

df_join_right

       ID      Lname      Fname                 Name Country
0  100001      Bogey    Hyberts       Bogey, Hyberts     USA
1  100002  Mireielle   Lindauer  Mireielle, Lindauer     USA
2  100003   Claiborn   Schacter   Claiborn, Schacter      UK
3  100008     Wendye  Cicinelli    Wendye, Cicinelli      UK
4  100009       Ethe     Slasor         Ethe, Slasor   China
5  100010  Valentine    Horsley   Valentine, Horsley     USA

In [ ]:
# Join dataframe and populate into a new dataframe with Left Outer Join such that Master Dataframe (df_masters) is on left, Secondary Dataframe (df_incoming) is on right
# TODO: Add your code here
df_join_left = pd.merge(df_masters, df_incoming, how='left', on=['ID'])
df_join_left

       ID      Lname      Fname                 Name Country
0  100001      Bogey    Hyberts       Bogey, Hyberts     USA
1  100002  Mireielle   Lindauer  Mireielle, Lindauer     USA
2  100003   Claiborn   Schacter   Claiborn, Schacter      UK
3  100004  Hildagard   Eberhart  Hildagard, Eberhart     NaN
4  100005      Welsh  Westerman     Welsh, Westerman     NaN
5  100006    Wrennie      Platt       Wrennie, Platt     NaN
6  100007     Barris   Reynales     Barris, Reynales     NaN
7  100008     Wendye  Cicinelli    Wendye, Cicinelli      UK
8  100009       Ethe     Slasor         Ethe, Slasor   China
9  100010  Valentine    Horsley   Valentine, Horsley     USA

In [ ]:
# Drop the column 'Name' from the dataframe
# TODO: Add your code here
df_join_left=df_join_left.drop(columns='Name')
df_join_left

       ID      Lname      Fname Country
0  100001      Bogey    Hyberts     USA
1  100002  Mireielle   Lindauer     USA
2  100003   Claiborn   Schacter      UK
3  100004  Hildagard   Eberhart     NaN
4  100005      Welsh  Westerman     NaN
5  100006    Wrennie      Platt     NaN
6  100007     Barris   Reynales     NaN
7  100008     Wendye  Cicinelli      UK
8  100009       Ethe     Slasor   China
9  100010  Valentine    Horsley     USA

In [ ]:
# Export the result of Left Outer Join into a CSV file
df_join_left.to_csv(file_out)